### PR TITLE
add Gemfile

### PR DESCRIPTION
**Pull request by hummusonrails**
Add a `Gemfile` to the skeleton app, so users can run it with `bundler`.

### CODE REVIEW

**Review by dragonmantank — APPROVED** [review]
LGTM, but probably need to bump this to use `vonage` instead

**Review by dragonmantank — CHANGES_REQUESTED** [review]
Nevermind, saw that this had already been partially updated. This needs to use the `vonage` gem

**Comment by hummusonrails** [comment]
@dragonmantank can you take another look when you get a chance? thx!

**Review by dragonmantank — APPROVED** [review]
LGTM :+1:

**Pull request merged**
